#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : asynctest
Version  : 0.13.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/0c/0f/6056f4435923d2f8c89ac9ef2d18506a569348d8f9cc827b0dd7a4c8acc4/asynctest-0.13.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/0c/0f/6056f4435923d2f8c89ac9ef2d18506a569348d8f9cc827b0dd7a4c8acc4/asynctest-0.13.0.tar.gz
Summary  : Enhance the standard unittest package with features for testing asyncio libraries
Group    : Development/Tools
License  : Apache-2.0
Requires: asynctest-python = %{version}-%{release}
Requires: asynctest-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
.. image:: https://img.shields.io/pypi/v/asynctest.svg
:target: https://pypi.python.org/pypi/asynctest
:alt: PyPI
.. image:: https://travis-ci.org/Martiusweb/asynctest.svg?branch=master
:target: https://travis-ci.org/Martiusweb/asynctest
:alt: Travis
.. image:: https://ci.appveyor.com/api/projects/status/github/Martiusweb/asynctest?branch=master&svg=true
:target: https://ci.appveyor.com/project/Martiusweb/asynctest/branch/master
:alt: AppVeyor
.. image:: https://img.shields.io/pypi/pyversions/asynctest.svg
:target: https://github.com/Martiusweb/asynctest
:alt: Supported Python versions

%package python
Summary: python components for the asynctest package.
Group: Default
Requires: asynctest-python3 = %{version}-%{release}

%description python
python components for the asynctest package.


%package python3
Summary: python3 components for the asynctest package.
Group: Default
Requires: python3-core
Provides: pypi(asynctest)

%description python3
python3 components for the asynctest package.


%prep
%setup -q -n asynctest-0.13.0
cd %{_builddir}/asynctest-0.13.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636414856
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
